-- MySQL Script generated by MySQL Workbench
-- ter 30 mai 2023 16:46:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`jogadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`jogadores` (
  `idjogadores` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idjogadores`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tree`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tree` (
  `idtree` INT NOT NULL,
  `depth` INT NOT NULL,
  `checkmate` TINYINT NOT NULL,
  `gameover` TINYINT NOT NULL,
  `update_at` TIMESTAMP NOT NULL,
  `jogadores_idjogadores` INT NULL,
  `tree_idtree` INT NOT NULL,
  PRIMARY KEY (`idtree`),
  INDEX `fk_tree_jogadores_idx` (`jogadores_idjogadores` ASC) VISIBLE,
  INDEX `fk_tree_tree1_idx` (`tree_idtree` ASC) VISIBLE,
  CONSTRAINT `fk_tree_jogadores`
    FOREIGN KEY (`jogadores_idjogadores`)
    REFERENCES `mydb`.`jogadores` (`idjogadores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tree_tree1`
    FOREIGN KEY (`tree_idtree`)
    REFERENCES `mydb`.`tree` (`idtree`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sessions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sessions` (
  `idSessions` INT NOT NULL,
  PRIMARY KEY (`idSessions`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transactions` (
  `idTransactions` INT NOT NULL,
  PRIMARY KEY (`idTransactions`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Interactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Interactions` (
  `idInteractions` INT NOT NULL,
  PRIMARY KEY (`idInteractions`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pontos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pontos` (
  `idpontos` INT NOT NULL,
  `valor` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idpontos`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
